version: '3.7'

services:

  frontend:
    container_name: frontend
    build: 
      context: ./frontend
      args:
        APP_NAME: $APP_NAME
        NODE_VERSION: $NODE_VERSION
    volumes:
      - ./:/app
    ports:
      - 3000:3000
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
